const messages={fa:{copied:'کد کپی شد.',manual:'کد انتخاب شد؛ برای کپی از Ctrl+C استفاده کنید.'}};
function normalizeTheme(value,systemDark){return value==='dark'||value==='light'?value:systemDark?'dark':'light'}
function copyFallbackText(code){return String(code||'').trim()}
function themeButtonState(theme){const dark=theme==='dark',label=dark?'فعال‌کردن تم روشن':'فعال‌کردن تم تیره';return{pressed:String(dark),label,title:label}}
function init(){const root=document.documentElement,menu=document.getElementById('course-menu-toggle'),side=document.getElementById('course-sidebar'),theme=document.getElementById('theme-toggle'),status=document.getElementById('copy-status');root.classList.add('course-ready');
 if(menu&&side){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));root.classList.toggle('menu-open',open)});side.addEventListener('click',e=>{if(e.target.closest('a')&&innerWidth<=800){menu.setAttribute('aria-expanded','false');root.classList.remove('menu-open')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');root.classList.remove('menu-open');menu.focus()}})}
 if(theme){const sync=()=>{const state=themeButtonState(root.dataset.theme);theme.setAttribute('aria-pressed',state.pressed);theme.setAttribute('aria-label',state.label);theme.title=state.title};sync();theme.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';sync();try{localStorage.setItem('dotnet-academy-theme',root.dataset.theme)}catch{}})}
 document.querySelectorAll('[data-copy-code]').forEach(btn=>btn.addEventListener('click',async()=>{const code=btn.closest('section').querySelector('code'),text=copyFallbackText(code.textContent);try{await navigator.clipboard.writeText(text);status.textContent=messages.fa.copied}catch{const range=document.createRange();range.selectNodeContents(code);getSelection().removeAllRanges();getSelection().addRange(range);status.textContent=messages.fa.manual}setTimeout(()=>status.textContent='',2500)}));}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',init);
if(typeof module!=='undefined')module.exports={normalizeTheme,copyFallbackText,themeButtonState,messages};
