module.exports={
  'value-vs-reference':{
    shortAnswer:'متغیر یک Value Type خودِ value را نگه می‌دارد؛ بنابراین assignment معمولاً یک کپی مستقل می‌سازد. متغیر یک Reference Type یک reference به یک object را نگه می‌دارد؛ assignment در این حالت reference را کپی می‌کند، نه خود object را.',
    mentalModel:'دو جعبه با نام a و b تصور کنید. اگر نوع آن‌ها Value Type باشد، هر جعبه نسخهٔ خودش از value را دارد. بعد از assign کردن a به b، تغییر b به a سرایت نمی‌کند. اگر نوع Reference Type باشد، هر جعبه یک نشانی دارد و هر دو نشانی می‌توانند به همان object برسند؛ تغییر object از مسیر b از مسیر a هم دیده می‌شود.',
    deepDive:'در مثال int، ابتدا a مقدار 10 دارد. عبارت b = a مقدار 10 را در متغیر جدید کپی می‌کند؛ پس بعد از b++، مقدار b برابر 11 و a همچنان 10 است. در مثال Person، عبارت second = first یک Person تازه نمی‌سازد. reference موجود در first کپی می‌شود و هر دو متغیر به همان object می‌رسند. به همین دلیل تغییر second.Name، property همان object مشترک را تغییر می‌دهد و first.Name نیز مقدار جدید را می‌بیند. نکتهٔ کلیدی این است که «متغیر» و «object» را یکی ندانیم.',
    exampleExplanation:'بعد از اجرای بخش اول، a=10 و b=11 است؛ دو value مستقل داریم. بعد از اجرای بخش دوم فقط یک Person ساخته شده است و first و second هر دو به آن اشاره می‌کنند. برای کپی مستقل یک Reference Type باید خودمان object دیگری بسازیم یا روش cloning متناسب با مدل را تعریف کنیم.',
    keyPoints:['Value Type در assignment دادهٔ خودش را کپی می‌کند.','Reference Type در assignment یک reference دیگر به همان object می‌سازد.','ارسال آرگومان به method به‌صورت پیش‌فرض by value است؛ برای Reference Type یعنی خود reference کپی می‌شود.'],
    furtherDetails:'این تفاوت را با جملهٔ «Value Type روی Stack و Reference Type روی Heap است» تعریف نکنید. محل storage به context وابسته است: یک field از نوع int می‌تواند داخل object روی Managed Heap قرار بگیرد و JIT نیز دربارهٔ نگه‌داری localها تصمیم می‌گیرد. دسته‌بندی زبان دربارهٔ semantics است، نه یک نقشهٔ ثابت Stack/Heap. struct و enum از Value Typeها هستند؛ class، array، delegate و string از Reference Typeها هستند.'
  },
  'boxing-unboxing':{
    shortAnswer:'Boxing زمانی رخ می‌دهد که یک Value Type به object یا یک interface سازگار تبدیل شود و CLR یک object شامل کپی value بسازد. Unboxing همان value را با بررسی type دقیق از object بیرون می‌آورد؛ این دو عملیات می‌توانند allocation، کپی و فشار بیشتر بر GC ایجاد کنند.',
    mentalModel:'یک int مستقیماً value عددی را نگه می‌دارد، اما متغیر object باید به یک object اشاره کند. برای قرارگرفتن int در object، CLR یک بستهٔ object می‌سازد و value را داخل آن کپی می‌کند؛ این همان Boxing است. Unboxing بازکردن دلخواه آن بسته نیست و فقط با type دقیق داخل آن معتبر است.',
    deepDive:'در object boxed = count، value فعلی count کپی و boxed می‌شود. تغییر بعدی count محتوای boxed را عوض نمی‌کند. عبارت (int)boxed ابتدا بررسی می‌کند object واقعاً یک boxed int است و سپس value را کپی می‌کند. اگر داخل object یک int باشد، cast مستقیم به long مجاز نیست؛ ابتدا باید int را Unbox و سپس conversion عددی انجام داد. استفاده از List<int> به‌جای collection غیر Generic باعث می‌شود elementها بدون Boxing ذخیره شوند.',
    exampleExplanation:'boxed یک snapshot از مقدار 42 است، نه اتصال زنده به count. `int copy = (int)boxed` موفق است؛ اما `(long)boxed` یک InvalidCastException ایجاد می‌کند، چون type boxed دقیقاً System.Int32 است. `long converted = (int)boxed` ابتدا Unboxing و سپس numeric conversion انجام می‌دهد.',
    keyPoints:['Boxing یک allocation و کپی value ایجاد می‌کند.','Unboxing به type دقیق boxed نیاز دارد.','Generic APIها معمولاً Boxing ناخواستهٔ Value Typeها را حذف می‌کنند.'],
    furtherDetails:'هر conversion به object الزاماً مشکل Performance مهمی نیست. اهمیت آن به تعداد تکرار و مسیر اجرا بستگی دارد. در hot pathها با profiler مقدار allocation را اندازه بگیرید. فراخوانی interface روی struct نیز در برخی شکل‌های استفاده می‌تواند Boxing ایجاد کند؛ Generic Constraint مناسب گاهی به JIT امکان فراخوانی بدون Boxing می‌دهد.'
  },
  'nullable-types':{
    shortAnswer:'Nullable Value Type مانند int? یک instance از Nullable<int> است و در Runtime حالت «دارای value» یا «بدون value» دارد. Nullable Reference Type مانند string? type جدیدی در CLR نیست؛ annotationای برای تحلیل جریان null توسط Compiler است.',
    mentalModel:'برای int معمولی، null جزو valueهای ممکن نیست. `int?` یک wrapper می‌سازد که علاوه بر int، وضعیت نبودن value را نگه می‌دارد. اما string از ابتدا می‌تواند در Runtime مقدار null بگیرد؛ علامت ? به Compiler می‌گوید این null در قرارداد برنامه مجاز است تا هشدارها دقیق‌تر شوند.',
    deepDive:'`int? score` شکل کوتاه `Nullable<int>` است و propertyهای HasValue و Value دارد. `score ?? 0` راه امنی برای fallback است. در مقابل، `string? name` و `string name` در metadata Runtime تا حد زیادی همان Reference Type هستند، ولی nullable annotations در metadata ثبت می‌شوند تا ابزارها و Compiler قرارداد را تحلیل کنند. فعال‌بودن Nullable Reference Types مانع ورود null در Runtime نمی‌شود؛ ورودی خارجی همچنان validation لازم دارد.',
    exampleExplanation:'وقتی score برابر null است، HasValue مقدار false دارد و دسترسی مستقیم به Value exception ایجاد می‌کند. `name?.Length ?? 0` اگر name برابر null باشد بدون dereference کردن آن، صفر برمی‌گرداند. این رفتار به‌معنای معتبر بودن business data نیست؛ فقط از NullReferenceException جلوگیری می‌کند.',
    keyPoints:['Nullable<T> یک struct واقعی برای Value Typeها است.','علامت ? روی Reference Type قرارداد و تحلیل Compiler را تغییر می‌دهد.','nullable analysis جای validation در مرزهای سیستم را نمی‌گیرد.'],
    furtherDetails:'عملگر null-forgiving یعنی ! فقط هشدار Compiler را خاموش می‌کند و هیچ check در Runtime اضافه نمی‌کند. attributeهایی مانند NotNullWhen و MemberNotNull برای بیان قراردادهای پیچیده‌تر به flow analysis کمک می‌کنند. در API عمومی، annotation باید رفتار واقعی را بیان کند؛ استفادهٔ بی‌رویه از ? یا ! ارزش تحلیل را از بین می‌برد.'
  },
  'var-object-dynamic':{
    shortAnswer:'var یعنی Compiler type دقیق متغیر را از expression سمت راست استنتاج می‌کند و type همچنان static است. object یک Reference Type عمومی با دسترسی static فقط به اعضای object است. dynamic بررسی member را تا Runtime عقب می‌اندازد.',
    mentalModel:'var را «نام کوتاه type» در نظر بگیرید، نه type پویا. پس از compile، متغیر var یک type مشخص مثل int دارد. object می‌تواند reference یا valueهای boxed را نگه دارد، اما برای اعضای اختصاصی باید type را narrow کنیم. dynamic به Compiler می‌گوید فعلاً بررسی نکن و operation را در Runtime resolve کن.',
    deepDive:'در `var total = 12`، total دقیقاً int است و بعداً نمی‌توان string در آن قرار داد. در `object value = "dotnet"`، object واقعی string است ولی type ایستای متغیر object است؛ pattern matching راه امن دسترسی به Length است. در dynamic، فراخوانی payload.Name compile می‌شود حتی اگر member وجود نداشته باشد و خطا ممکن است تازه در Runtime آشکار شود. dynamic برای مرزهای واقعاً پویا مفید است، نه جایگزین طراحی type-safe.',
    exampleExplanation:'Compiler برای total تمام خطاهای مربوط به int را در Compile Time پیدا می‌کند. pattern `value is string text` هم type را بررسی و هم متغیر typed ایجاد می‌کند. اگر object بازگشتی در مثال dynamic فاقد Name باشد، RuntimeBinderException رخ می‌دهد؛ IDE و refactoring نیز تضمین کمتری دارند.',
    keyPoints:['var با Static Typing کاملاً سازگار است.','object برای استفاده از عضو اختصاصی به cast یا pattern matching نیاز دارد.','dynamic انعطاف را با انتقال خطا و بخشی از هزینه به Runtime به دست می‌آورد.'],
    furtherDetails:'نوع anonymous localها اغلب فقط با var قابل نام‌گذاری عملی است. dynamic در interop با COM، دادهٔ پویا یا برخی proxyها مفید است؛ بهتر است آن را در یک boundary کوچک نگه دارید و سریعاً به model typed تبدیل کنید. هر سه گزینه نوعی ابزارند و انتخاب آن‌ها باید قرارداد API را روشن‌تر کند.'
  },
  'clr-type-system':{
    shortAnswer:'C# typeها را در metadata و IL مطابق Common Type System یا CTS توصیف می‌کند. CLR این اطلاعات را برای loading، type safety، Genericها و JIT compilation استفاده می‌کند؛ CLS نیز زیرمجموعه‌ای از قواعد برای interoperability بهتر میان زبان‌ها است.',
    mentalModel:'C# تنها زبان روی .NET نیست. هر زبان syntax خودش را دارد، اما خروجی آن باید بتواند type، member و رابطه‌ها را با قرارداد مشترکی توصیف کند که CLR بفهمد. CTS این واژگان مشترک را فراهم می‌کند و metadata مانند شناسنامهٔ typeها در assembly است.',
    deepDive:'Compiler تعریف class، field، method، Generic Constraint و visibility را در metadata ثبت و body methodها را به IL تبدیل می‌کند. CLR هنگام load کردن assembly سازگاری typeها را بررسی می‌کند و JIT برای methodهای موردنیاز machine code می‌سازد. CTS میان Value Type و Reference Type، inheritance، interface و memberها تمایز می‌گذارد. CLS همهٔ CTS نیست؛ مجموعه‌ای از قواعد است که API عمومی با رعایت آن برای زبان‌های بیشتری قابل مصرف می‌شود.',
    exampleExplanation:'در مثال Counter، metadata وجود type sealed، constructor، property و type بازگشتی آن را توصیف می‌کند. مصرف‌کنندهٔ نوشته‌شده با زبان .NET دیگر بدون دیدن source C# می‌تواند همین قرارداد را بخواند. implementation method در IL ذخیره شده و CLR/JIT آن را اجرا می‌کند.',
    keyPoints:['CTS مدل مشترک typeها در CLR است.','metadata قرارداد type و IL رفتار method را حمل می‌کنند.','CLS برای interoperability API عمومی است و با CTS یکسان نیست.'],
    furtherDetails:'هر type در C# مستقیم یا غیرمستقیم با System.Object مرتبط است؛ Value Typeها از System.ValueType مشتق می‌شوند، ولی System.ValueType خودش یک class است. JIT و Runtime ممکن است implementation را بهینه کنند، بنابراین از نتیجه‌گیری‌های ثابت دربارهٔ layout یا machine code بدون اندازه‌گیری پرهیز کنید.'
  },
  'logical-and':{
    shortAnswer:'برای operandهای bool، && یک Conditional AND با Short-Circuit Evaluation است؛ اگر سمت چپ false باشد سمت راست اجرا نمی‌شود. & روی bool هر دو operand را ارزیابی می‌کند و روی integerها Bitwise AND است.',
    mentalModel:'نتیجهٔ false && هرچیزی از همان سمت چپ مشخص است، پس C# می‌تواند سمت راست را رد کند. این توقف زودهنگام فقط بهینه‌سازی نیست؛ بخشی از semantics && است و برای guard کردن دسترسی‌های خطرناک استفاده می‌شود. & چنین توقفی ندارد.',
    deepDive:'در `user is not null && user.IsActive`، property فقط وقتی خوانده می‌شود که user null نباشد. جایگزین‌کردن && با & باعث ارزیابی user.IsActive و احتمال NullReferenceException می‌شود. در `CheckA() & CheckB()` هر دو method اجرا می‌شوند، حتی اگر اولی false دهد؛ این رفتار با side effectها قابل مشاهده است. برای integer، هر bit متناظر مقایسه می‌شود و فقط 1 & 1 نتیجهٔ 1 دارد.',
    exampleExplanation:'عبارت safe بدون exception مقدار false می‌گیرد اگر user null باشد. در مثال bothRun هر دو log یا side effect اجرا می‌شوند. mask فقط دو bit پایین flags را نگه می‌دارد؛ این کاربرد هیچ ارتباطی با شرط boolean ندارد.',
    keyPoints:['&& سمت راست را در صورت false بودن سمت چپ اجرا نمی‌کند.','& روی bool هر دو طرف را اجرا می‌کند.','& روی integer عملیات Bitwise AND انجام می‌دهد.'],
    furtherDetails:'operatorهای && و || مستقیماً overload نمی‌شوند، اما type می‌تواند operatorهای true/false و & یا | را تعریف کند تا conditional logic سفارشی ممکن شود. در کد عادی، && انتخاب پیش‌فرض شرط‌ها است؛ & را فقط وقتی semantics eager یا bit mask را واقعاً می‌خواهید به‌کار ببرید.'
  },
  'conditional-operator':{
    shortAnswer:'Conditional Operator یعنی `condition ? whenTrue : whenFalse` یک expression است که یکی از دو value را تولید می‌کند. برای انتخاب کوتاه یک value مناسب است؛ اگر هر branch چند کار انجام می‌دهد یا خوانایی افت می‌کند، if روشن‌تر است.',
    mentalModel:'if مسیر اجرای statementها را کنترل می‌کند، ولی Conditional Operator خودش یک value دارد. به همین دلیل می‌توان آن را در assignment، return یا argument قرار داد. تنها یکی از دو branch ارزیابی می‌شود، پس branch انتخاب‌نشده side effect یا exception ایجاد نمی‌کند.',
    deepDive:'در `var label = score >= 10 ? "قبول" : "نیازمند تلاش"` هدف فقط انتخاب یک string است و شکل expression خواناست. اگر branchها نیاز به log، validation و چند statement داشته باشند، فشرده‌کردن آن‌ها در expression فهم کد را سخت می‌کند. Conditional Operator می‌تواند target-typed باشد؛ context مقصد به Compiler کمک می‌کند type مشترک branchها را تعیین کند.',
    exampleExplanation:'برای score برابر 12 فقط expression نخست اجرا و label برابر «قبول» می‌شود. در return دوم، اگر user null باشد Result.NotFound ساخته می‌شود و Result.Ok اصلاً فراخوانی نمی‌شود. این lazy branch selection با فراخوانی هر دو method و انتخاب نتیجه متفاوت است.',
    keyPoints:['Conditional Operator یک value تولید می‌کند.','فقط branch انتخاب‌شده ارزیابی می‌شود.','خوانایی مهم‌تر از کوتاه‌کردن ظاهری کد است.'],
    furtherDetails:'زنجیرهٔ nested از `?:` از نظر syntax ممکن است، اما ترتیب association و scan کردن آن دشوار می‌شود. برای mappingهای کوچک مناسب است؛ برای business rule چندشاخه، switch expression یا method نام‌دار معمولاً intent را بهتر منتقل می‌کند.'
  },
  'null-operators':{
    shortAnswer:'?? در صورت null بودن operand چپ fallback می‌دهد؛ ??= فقط در همان حالت assignment می‌کند؛ ?. و ?[] دسترسی member یا index را متوقف کرده و نتیجهٔ null می‌دهند اگر receiver null باشد.',
    mentalModel:'این operatorها یک مسیر امن برای «نبودن value» می‌سازند. ?? میان value موجود و fallback انتخاب می‌کند. ?. پیش از دسترسی می‌پرسد آیا object وجود دارد؛ اگر نه، ادامهٔ زنجیره را اجرا نمی‌کند. این رفتار exceptionهای دیگر را پنهان نمی‌کند.',
    deepDive:'در `customer?.Address?.City ?? "نامشخص"` هر access فقط وقتی ادامه پیدا می‌کند که نتیجهٔ قبلی null نباشد. سمت راست ?? lazy است، بنابراین fallback گران فقط در صورت نیاز ساخته می‌شود. `cache ??= new Dictionary...` initialization را انجام می‌دهد اگر cache null باشد، اما به‌تنهایی primitive همگام‌سازی threadها نیست. ?[] همان conditional access برای indexer است.',
    exampleExplanation:'اگر customer یا Address null باشد، city برابر «نامشخص» می‌شود. اگر getter مربوط به City exception دیگری پرتاب کند، ?. آن را catch نمی‌کند. اگر cache از قبل ساخته شده باشد، constructor سمت راست ??= اجرا نمی‌شود.',
    keyPoints:['?? و ??= سمت راست را فقط هنگام نیاز ارزیابی می‌کنند.','?. و ?[] فقط null receiver را مدیریت می‌کنند.','fallback نباید نبودن دادهٔ الزامی را بی‌صدا پنهان کند.'],
    furtherDetails:'چند operator را می‌توان ترکیب کرد، ولی زنجیرهٔ طولانی ممکن است معلوم نکند کدام داده غایب بوده است. در domain invariant یا ورودی الزامی، validation و خطای صریح بهتر است. `throw` expression نیز می‌تواند سمت راست ?? قرار گیرد تا قرارداد non-null enforce شود.'
  },
  'foreach-lowering':{
    shortAnswer:'foreach از یک enumeration pattern استفاده می‌کند: دریافت enumerator، فراخوانی MoveNext، خواندن Current و در صورت نیاز Dispose. Compiler براساس type ایستای collection و pattern موجود شکل مناسب کد را تولید می‌کند.',
    mentalModel:'foreach جادو نیست؛ یک cursor روی sequence حرکت می‌کند. هر بار MoveNext می‌پرسد element بعدی وجود دارد یا نه و Current همان element را می‌دهد. loop body با آن value اجرا می‌شود و در پایان resource مربوط به enumerator آزاد می‌شود.',
    deepDive:'Compiler ابتدا collection type، enumerator type و iteration type را تعیین می‌کند. اگر pattern مناسب GetEnumerator/MoveNext/Current وجود داشته باشد، الزاماً نیاز نیست type مستقیماً IEnumerable<T> را پیاده کند. برای array ممکن است lowering به شکل بهینهٔ index-based انجام شود. اگر enumerator disposable باشد، cleanup در ساختاری شبیه try/finally قرار می‌گیرد. `ref` و `ref readonly foreach` نیز برای iteration روی reference به element قواعد جدا دارند.',
    exampleExplanation:'کد while مفهوم پایه را نشان می‌دهد: e یک بار ساخته می‌شود، MoveNext پیش می‌رود و Current فقط پس از موفقیت آن خوانده می‌شود. using تضمین می‌کند Dispose اجرا شود. این کد ترجمهٔ دقیق تمام foreachها نیست؛ Compiler برای typeهای خاص بهینه‌سازی متفاوتی دارد.',
    keyPoints:['foreach بر enumeration pattern تکیه دارد.','Current پس از موفقیت MoveNext معتبر است.','نوع ایستای collection می‌تواند بر allocation و dispatch اثر بگذارد.'],
    furtherDetails:'یک struct enumerator می‌تواند allocation را حذف کند، اما تبدیل آن به interface ممکن است Boxing بسازد. تغییر ساختاری collection هنگام enumeration معمولاً enumerator را invalid می‌کند. برای Performance، foreach را کورکورانه با for جایگزین نکنید؛ generated code و workload واقعی را Benchmark کنید.'
  },
  'checked-unchecked':{
    shortAnswer:'checked برای arithmetic و conversionهای integral مشخص می‌کند Overflow باید OverflowException ایجاد کند؛ unchecked wrap شدن نتیجه را طبق representation مقصد مجاز می‌کند. این رفتار برای floating-point و decimal یکسان نیست.',
    mentalModel:'اگر int.MaxValue را یک واحد زیاد کنیم، نتیجه در int جا نمی‌شود. checked این خارج‌شدن از محدوده را خطا می‌داند. unchecked bitهای اضافه را کنار می‌گذارد و value از سمت دیگر محدوده ظاهر می‌شود. انتخاب باید براساس معنی داده باشد، نه راحتی عبور از خطا.',
    deepDive:'`checked(max + 1)` در Runtime OverflowException می‌دهد. `unchecked(max + 1)` معمولاً int.MinValue تولید می‌کند. constant expressionهای خارج از محدوده اغلب در Compile Time رد می‌شوند و unchecked می‌تواند intent را صریح کند. decimal همیشه Overflow را بررسی می‌کند، درحالی‌که floating-point به Infinity می‌رسد و checked آن را به integer semantics تبدیل نمی‌کند.',
    exampleExplanation:'در try نخست exception گرفته می‌شود و next ساخته نمی‌شود. wrapped برابر -2147483648 خواهد بود. این wrap برای محاسبهٔ مالی یا تعداد امنیتی معمولاً bug است، ولی در برخی الگوریتم‌های Hash بخشی عمدی از طراحی است.',
    keyPoints:['checked روی عملیات و conversionهای integral اثر می‌گذارد.','unchecked wrap را صریحاً می‌پذیرد.','نوع عددی و context Compile Time یا Runtime در نتیجه مهم است.'],
    furtherDetails:'تنظیم CheckForOverflowUnderflow پروژه می‌تواند context پیش‌فرض برخی عملیات را تغییر دهد، اما بهتر است boundaryهای حساس با checked صریح باشند. این setting روی هر operation به یک شکل اثر ندارد؛ مستندات operation و type را بررسی کنید.'
  },
  'class-struct-record':{
    shortAnswer:'`class` یک Reference Type با identity است؛ `struct` یک Value Type است که با assignment کپی می‌شود؛ `record` برای مدل‌های داده‌محور، Value Equality و syntax کم‌حجم طراحی شده و می‌تواند `record class` یا `record struct` باشد.',
    mentalModel:'برای انتخاب، ابتدا بپرسید داده «هویت» دارد یا فقط «مقدار» است. دو Customer با مشخصات یکسان ممکن است دو موجودیت جدا باشند، پس `class` طبیعی است. دو Coordinate با X و Y برابر یک مقدار را نشان می‌دهند، پس `struct` می‌تواند مناسب باشد. `record` وقتی مفید است که equality و نمایش داده بخش اصلی مدل باشند.',
    deepDive:'assignment یک `class` فقط reference را کپی می‌کند و هر دو متغیر همان object را می‌بینند. assignment یک `struct` تمام state آن value را کپی می‌کند؛ تغییر copy به اصل سرایت نمی‌کند، مگر اینکه خود struct referenceای به object mutable داشته باشد. `record class` هنوز Reference Type است اما Compiler برای اعضای اصلی Value Equality، `GetHashCode` و `with` را تولید می‌کند. `record struct` Value Type است و رفتار کپی Value Type را حفظ می‌کند. انتخاب فقط با اندازه یا Performance انجام نمی‌شود؛ semantics دامنه مقدم است.',
    exampleExplanation:'در مثال، تغییر `customer2.Name` روی `customer1` دیده می‌شود چون هر دو reference به یک object هستند. تغییر `point2.X` روی `point1` اثری ندارد چون Coordinate کپی شده است. دو `Money` record با Amount و Currency برابر، با `==` برابرند؛ این equality به داده‌ها مربوط است، نه یکی‌بودن object.',
    keyPoints:['`class` برای identity و state مشترک مناسب است.','`struct` با assignment یک value مستقل کپی می‌کند.','`record` equality و syntax داده‌محور را فراهم می‌کند و الزاماً Value Type نیست.'],
    furtherDetails:'structهای بزرگ یا mutable می‌توانند کپی‌های پرهزینه و رفتار گیج‌کننده بسازند؛ کوچک و preferably immutable نگه‌داشتن آن‌ها معمولاً انتخاب امن‌تری است. `readonly struct` جلوی تغییر state پس از ساخت را می‌گیرد. برای record نیز دقت کنید `with` یک shallow copy است و objectهای mutable تو‌در‌تو را clone عمیق نمی‌کند.'
  },
  'overload-override-hide':{
    shortAnswer:'Overloading انتخاب میان signatureهای هم‌نام در Compile Time است. Overriding پیاده‌سازی یک member `virtual` یا `abstract` را عوض می‌کند و انتخاب آن در Runtime انجام می‌شود. Method Hiding با `new` member پایه را براساس Static Type پنهان می‌کند.',
    mentalModel:'سه پرسش جدا بپرسید: آیا چند method هم‌نام با parameterهای متفاوت داریم؟ Overloading. آیا call از reference پایه باید رفتار type واقعی object را اجرا کند؟ Overriding. آیا member جدید فقط وقتی متغیر با type مشتق دیده می‌شود انتخاب شود؟ Method Hiding. یکی‌کردن این سه باعث پاسخ مبهم می‌شود.',
    deepDive:'در Overloading، Compiler با typeهای قابل‌مشاهده و قواعد conversion بهترین signature را انتخاب می‌کند؛ Runtime Type آرگومان به‌تنهایی overload دیگری را فعال نمی‌کند. در Overriding، member پایه باید `virtual` یا `abstract` باشد و عضو مشتق با `override` همان slot مجازی را پیاده کند؛ dispatch با Runtime Type object انجام می‌شود. در Method Hiding، member مشتق slot تازه‌ای دارد و call براساس Static Type سمت چپ تعیین می‌شود. استفاده از `new` هشدار را صریح می‌کند ولی رفتار را polymorphic نمی‌سازد.',
    exampleExplanation:'اگر `Animal a = new Dog()` باشد، `a.Speak()` نسخه `Dog` را اجرا می‌کند چون Speak override شده است. اما اگر `Info` با `new` پنهان شده باشد، `a.Info()` نسخه `Animal` را می‌خواند و `((Dog)a).Info()` نسخه Dog را. overload `Print(int)` یا `Print(string)` نیز هنگام Compile براساس type آرگومان انتخاب می‌شود.',
    keyPoints:['Overloading به signature و Compile Time مربوط است.','Overriding از virtual dispatch و Runtime Type استفاده می‌کند.','Method Hiding به Static Type متغیر وابسته است.'],
    furtherDetails:'return type به‌تنهایی overload نمی‌سازد. در override باید accessibility و قرارداد base رعایت شود و امکان covariant return برای برخی reference return typeها وجود دارد. Method Hiding معمولاً در API عمومی غافلگیرکننده است؛ اگر polymorphism هدف است، طراحی virtual/override یا Composition روشن‌تر خواهد بود.'
  },
  'interface-vs-abstract':{
    shortAnswer:'`interface` قرارداد یک capability را تعریف می‌کند و یک type می‌تواند چند interface را پیاده کند. `abstract class` علاوه بر قرارداد، state، constructor، protected member و implementation مشترک برای یک خانواده نزدیک از typeها فراهم می‌کند.',
    mentalModel:'interface می‌گوید «این object چه کاری می‌تواند انجام دهد؟»؛ مانند `IPrintable`. abstract class می‌گوید «این object عضو چه خانواده‌ای است و چه state و invariant مشترکی دارد؟»؛ مانند `Document`. اگر فقط مصرف‌کننده به یک قابلیت نیاز دارد، interface coupling کمتری ایجاد می‌کند. اگر lifecycle و state مشترک داریم، base class می‌تواند مناسب‌تر باشد.',
    deepDive:'یک class تنها از یک class ارث می‌برد ولی می‌تواند چند interface داشته باشد، بنابراین interface برای مرزهای قابل‌تعویض، testing و ترکیب capabilityها مناسب است. interfaceهای جدید می‌توانند Default Interface Member داشته باشند، اما جایگزین state instance، constructor و protected workflow یک abstract class نیستند. abstract class می‌تواند template method بسازد و invariantها را در یک مسیر کنترل کند؛ در عوض coupling وراثتی ایجاد می‌کند و evolution آن بر تمام derived typeها اثر دارد.',
    exampleExplanation:'`EmailSender` و `SmsSender` هر دو `INotifier` را پیاده می‌کنند و سرویس مصرف‌کننده فقط Send را می‌بیند. اگر همه notificationها retry count، validation مقصد و یک workflow مشترک داشته باشند، `NotificationBase` می‌تواند این state و sequence را نگه دارد. ممکن است class هم از base استفاده کند و هم چند interface ارائه دهد.',
    keyPoints:['interface قرارداد capability و چندپیاده‌سازی را ممکن می‌کند.','abstract class برای state و invariant مشترک مناسب است.','انتخاب به رابطه دامنه و نیاز مصرف‌کننده وابسته است، نه تعداد memberها.'],
    furtherDetails:'interface بسیار بزرگ به God Interface تبدیل می‌شود؛ قراردادها را حول نیاز مصرف‌کننده کوچک نگه دارید. base class شکننده نیز derived classها را به جزئیات داخلی وابسته می‌کند. قبل از Inheritance، Composition را بررسی کنید: گاهی inject کردن یک strategy هم reuse می‌دهد و هم coupling کمتری دارد.'
  },
  'runtime-polymorphism':{
    shortAnswer:'Runtime Polymorphism یعنی call یک member مجازی از طریق reference پایه یا interface، implementation متناسب با Runtime Type واقعی object را اجرا کند. این رفتار با `virtual`/`override`، `abstract`/`override` یا interface dispatch شکل می‌گیرد.',
    mentalModel:'متغیر دو type مرتبط دارد: Static Type مشخص می‌کند چه memberهایی قابل فراخوانی‌اند؛ Runtime Type مشخص می‌کند کدام override اجرا شود. در `Shape shape = new Circle()`، Compiler فقط قرارداد Shape را می‌بیند، اما هنگام `shape.Area()`، Runtime پیاده‌سازی Circle را انتخاب می‌کند.',
    deepDive:'Compiler برای call مجازی instruction و metadata لازم را تولید می‌کند و CLR slot مناسب Runtime Type را dispatch می‌کند. شرط آن است که member واقعاً virtual باشد؛ method عادی یا member `static` از این مسیر استفاده نمی‌کند. interface dispatch نیز implementation type واقعی را پیدا می‌کند. Runtime Polymorphism به مصرف‌کننده اجازه می‌دهد بدون `if` روی typeهای مشخص، با قرارداد پایه کار کند؛ افزودن implementation جدید معمولاً مصرف‌کننده را تغییر نمی‌دهد.',
    exampleExplanation:'حلقه روی `IEnumerable<Shape>` فقط `Area()` را فراخوانی می‌کند. برای Circle فرمول دایره و برای Rectangle فرمول مستطیل اجرا می‌شود، با اینکه type متغیر حلقه Shape است. اگر Area در base virtual نباشد و فقط در derived هم‌نام تعریف شود، این نتیجه به‌دست نمی‌آید.',
    keyPoints:['Static Type سطح قرارداد قابل‌مشاهده را تعیین می‌کند.','Runtime Type override واقعی را برای call مجازی انتخاب می‌کند.','Polymorphism شرط‌گذاری روی typeهای concrete را کاهش می‌دهد.'],
    furtherDetails:'constructorها virtual نیستند و فراخوانی member مجازی از constructor پایه خطرناک است، چون state بخش مشتق شاید هنوز کامل نشده باشد. CLR ممکن است call را devirtualize و inline کند بدون تغییر semantics. برای correctness روی قرارداد تکیه کنید و برای Performance خروجی Benchmark و JIT را بررسی کنید.'
  },
  'composition-vs-inheritance':{
    shortAnswer:'Inheritance رابطه پایدار «is-a» و substitutability می‌سازد؛ Composition رفتار را با نگه‌داشتن و واگذاری کار به objectهای دیگر ترکیب می‌کند. وقتی فقط reuse رفتار لازم است، Composition معمولاً انعطاف و coupling بهتری دارد.',
    mentalModel:'اگر هرجا Base پذیرفته می‌شود Derived بدون شکستن انتظارها قابل استفاده است، Inheritance ممکن است درست باشد. اگر object فقط به یک رفتار نیاز دارد، آن رفتار را به‌صورت dependency نگه دارید. Car یک Engine «دارد»، پس Composition طبیعی است؛ Circle یک Shape «است»، پس Inheritance یا interface می‌تواند طبیعی باشد.',
    deepDive:'Inheritance implementation و lifecycle را به base گره می‌زند و تغییر protected behavior می‌تواند derived typeها را بشکند. طبق Liskov Substitution Principle، derived type نباید precondition را سخت‌تر، postcondition را ضعیف‌تر یا invariant base را نقض کند. Composition این رابطه را به همکاری objectها تبدیل می‌کند؛ strategy در Runtime قابل تعویض، مستقل قابل test و جدا قابل توسعه است. هزینه آن تعداد object و wiring بیشتر است.',
    exampleExplanation:'`ReportService` یک `IFormatter` دریافت می‌کند. برای PDF یا JSON فقط formatter دیگری inject می‌شود و خود سرویس تغییر نمی‌کند. اگر ReportService از PdfFormatter ارث می‌برد، تبدیل رفتار به JSON رابطه «is-a» جعلی می‌ساخت و reuse را به hierarchy وابسته می‌کرد.',
    keyPoints:['Inheritance باید substitutability واقعی داشته باشد.','Composition رفتار را از طریق dependency و delegation می‌سازد.','reuse کد به‌تنهایی دلیل کافی برای Inheritance نیست.'],
    furtherDetails:'Inheritance برای framework hook یا hierarchy دامنه پایدار می‌تواند عالی باشد. Composition نیز اگر interfaceهای بی‌معنا و delegationهای طولانی بسازد، بیش‌طراحی است. معیار عملی این است: آیا تغییر مستقل رفتار و testing جدا ارزش دارد، و آیا مصرف‌کننده واقعاً باید type مشتق را همان base بداند؟'
  },
  'record-vs-class':{
    shortAnswer:'`record class` مانند `class` یک Reference Type است، اما به‌صورت پیش‌فرض Value Equality، نمایش مناسب و `with` expression دارد. `class` عادی به‌صورت پیش‌فرض Reference Equality دارد و برای entityهای دارای identity معمولاً روشن‌تر است.',
    mentalModel:'برای entity بپرسید «آیا دو instance با داده یکسان هنوز دو چیز جدا هستند؟» اگر بله، class با identity مناسب است. برای data carrier بپرسید «آیا تمام معنای object از مقدار memberها می‌آید؟» اگر بله، record می‌تواند equality و copy موردنیاز را کم‌هزینه‌تر بیان کند.',
    deepDive:'Compiler برای record memberهای equality، `GetHashCode`، `ToString` و سازوکار `with` را تولید می‌کند. این به معنی immutable بودن مطلق نیست؛ propertyهای mutable همچنان قابل تغییرند. `with` یک shallow copy می‌سازد، بنابراین referenceهای داخل record بین نسخه‌ها مشترک می‌مانند. class عادی نیز می‌تواند Value Equality را دستی پیاده کند، و record نیز می‌تواند identity داشته باشد، اما defaultهای هرکدام intent متفاوتی منتقل می‌کنند.',
    exampleExplanation:'دو `Money("USD", 10)` record با `==` برابرند چون componentهایشان برابر است. دو `Customer` class با نام یکسان به‌صورت پیش‌فرض برابر نیستند چون instanceهای جدا هستند. `order2 = order1 with { Status = "Paid" }` object بیرونی تازه می‌سازد، ولی اگر Items یک List باشد همان List می‌تواند مشترک بماند.',
    keyPoints:['record class هنوز Reference Type است.','record به‌صورت پیش‌فرض Value Equality دارد.','`with` shallow copy است و immutable بودن عمیق تضمین نمی‌کند.'],
    furtherDetails:'در Entity Framework و modelهای identityمحور باید اثر equality تولیدشده را آگاهانه بررسی کنید. record برای DTO، command، event و value object بسیار مناسب است. برای object دارای lifecycle و mutable state گسترده، class عادی معمولاً intent را شفاف‌تر نشان می‌دهد.'
  },
  'record-value-equality':{
    shortAnswer:'Value Equality در record یعنی دو instance وقتی برابرند که Runtime Type سازگار و componentهای equality آن‌ها برابر باشند. Compiler `Equals`، `==` و `GetHashCode` هماهنگ تولید می‌کند.',
    mentalModel:'به‌جای پرسیدن «آیا این دو متغیر به یک object اشاره می‌کنند؟»، record می‌پرسد «آیا داده‌ای که این value را تعریف می‌کند برابر است؟». مثل دو اسکناس دیجیتال با Currency و Amount یکسان. بااین‌حال اگر component داخلی خودش Reference Equality داشته باشد، record آن را خودکار به deep equality تبدیل نمی‌کند.',
    deepDive:'برای positional record، propertyهای اصلی وارد equality می‌شوند و memberهای instance مرتبط نیز طبق قواعد تولیدشده مشارکت دارند. `EqualityContract` کمک می‌کند recordهای derived با type متفاوت صرفاً به‌خاطر componentهای مشابه برابر نشوند. `GetHashCode` باید با equality سازگار بماند؛ تغییر member مؤثر در equality پس از قراردادن record در `Dictionary` یا `HashSet` می‌تواند lookup را خراب کند. memberهای collection نیز equality خودشان را به record منتقل می‌کنند.',
    exampleExplanation:'دو `Point(2, 3)` برابر و hash آن‌ها سازگار است. اما دو record که هرکدام یک `List<int>` جدا با عناصر یکسان دارند، الزاماً برابر نیستند چون List به‌صورت پیش‌فرض reference-based مقایسه می‌شود. همچنین mutation یک property پس از افزودن به HashSet ممکن است object را در bucket اشتباه باقی بگذارد.',
    keyPoints:['equality تولیدشده به componentها و Runtime Type وابسته است.','componentهای nested رفتار equality خود را حفظ می‌کنند.','member مؤثر در hash نباید هنگام عضویت در hash collection تغییر کند.'],
    furtherDetails:'اگر deep structural equality برای collectionها لازم است، یک type مناسب immutable یا comparer صریح طراحی کنید. override کردن equality record ممکن است، اما باید `Equals` و `GetHashCode` هماهنگ بمانند. برای امنیت طراحی، recordهای استفاده‌شده به‌عنوان key را immutable نگه دارید.'
  },
  'record-kinds':{
    shortAnswer:'`record` و `record class` Reference Type هستند؛ `record struct` Value Type است؛ `readonly record struct` نیز Value Type است و تغییر propertyهای instance را محدود می‌کند. هرکدام Value Equality تولیدشده دارند، اما copy semantics آن‌ها متفاوت است.',
    mentalModel:'واژه record شکل equality و data-oriented syntax را انتخاب می‌کند؛ واژه class یا struct خانواده type و رفتار assignment را. بنابراین ابتدا Reference Type یا Value Type بودن را تصمیم بگیرید، سپس از مزایای record استفاده کنید. record بدون واژه دوم همان record class است.',
    deepDive:'record class با assignment reference را کپی می‌کند و `with` object بیرونی تازه‌ای می‌سازد. record struct در assignment خود value را کپی می‌کند و به‌صورت پیش‌فرض می‌تواند mutable باشد. `readonly record struct` برای value کوچک و immutable مناسب است و Compiler از mutation اعضای instance جلوگیری می‌کند. positional syntax برای هر سه constructor و propertyهای اصلی را می‌سازد، ولی نوع property تولیدشده و امکان set/init طبق شکل declaration تفاوت دارد.',
    exampleExplanation:'`PersonRecord` که record class است با assignment مشترک می‌ماند، اما `PointRecord` که record struct است در assignment مستقل کپی می‌شود. `readonly record struct Money(decimal Amount, string Currency)` اجازه نمی‌دهد پس از ساخت Amount تغییر کند و برای یک value کوچک intent واضحی دارد.',
    keyPoints:['record بدون qualifier همان record class است.','record struct رفتار کپی Value Type دارد.','readonly record struct برای value کوچک و immutable مناسب است.'],
    furtherDetails:'بزرگ‌کردن record struct هزینه کپی را بالا می‌برد و memberهای reference داخل آن همچنان به object مشترک اشاره می‌کنند. `readonly` فقط خود fieldها و propertyهای instance را محدود می‌کند و objectهای nested را immutable نمی‌سازد. انتخاب نهایی باید با semantics و سپس اندازه‌گیری Performance انجام شود.'
  },
  'anonymous-types':{
    shortAnswer:'Anonymous Type یک Reference Type تولیدشده توسط Compiler با propertyهای فقط‌خواندنی است که معمولاً برای projection محلی، به‌ویژه در LINQ، استفاده می‌شود. نام قابل‌استفاده‌ای برای قرارداد عمومی API ندارد.',
    mentalModel:'وقتی داخل یک method فقط موقتاً به ترکیب `Name` و `Total` نیاز دارید، ساخت class نام‌دار ممکن است اضافه باشد. `new { order.Name, Total = order.Items.Sum(...) }` یک shape محلی می‌سازد. اگر داده باید از مرز method، assembly، serialization contract یا لایه عبور کند، type نام‌دار intent بهتری می‌دهد.',
    deepDive:'Compiler یک class داخلی با propertyهای inferred، constructor، Value Equality، `GetHashCode` و `ToString` تولید می‌کند. propertyها پس از construction قابل set نیستند، هرچند objectهایی که داخلشان قرار دارد می‌توانند mutable باشند. دو anonymous object در یک assembly با نام، ترتیب و type propertyهای یکسان می‌توانند از یک type تولیدشده مشترک استفاده کنند. چون نام type در source قابل بیان نیست، return عمومی معمولاً به `object` یا `dynamic` منجر می‌شود و type safety را از دست می‌دهد.',
    exampleExplanation:'projection فهرست سفارش‌ها فقط `Id` و `Total` را برای مرتب‌سازی داخلی نگه می‌دارد، پس Anonymous Type مناسب است. اگر همین داده باید از controller برگردد، `OrderSummaryDto` بهتر است تا قرارداد، validation و تغییر نسخه روشن باشند. property فقط‌خواندنی است، ولی اگر مقدار آن List باشد خود List هنوز تغییرپذیر است.',
    keyPoints:['Anonymous Type برای shape موقت و محلی مناسب است.','propertyها فقط‌خواندنی‌اند اما deep immutable نیستند.','برای مرز عمومی یا قرارداد پایدار از type نام‌دار استفاده کنید.'],
    furtherDetails:'در query providerهایی مانند Entity Framework، expression projection به Anonymous Type می‌تواند به query سمت server ترجمه شود. این یک مزیت کاربردی است، اما نباید type ناشناس را با hackهای reflection از مرز لایه‌ها عبور داد. record یا DTO نام‌دار برای reuse و مستندسازی بهتر است.'
  },
  'tuple-choices':{
    shortAnswer:'`ValueTuple` مانند `(int Id, string Name)` یک Value Type کم‌حجم برای چند خروجی موقت است؛ `Tuple<T...>` یک Reference Type قدیمی‌تر است؛ type نام‌دار مانند record وقتی معنا، validation یا قرارداد پایدار مهم است انتخاب بهتری است.',
    mentalModel:'Tuple یک بسته موقت از چند value است، نه یک مدل دامنه کامل. اگر caller بلافاصله نتیجه را باز می‌کند و نام‌ها واضح‌اند، `(bool Found, User? User)` خواناست. اگر داده در چند لایه حرکت می‌کند یا rule دارد، `UserLookupResult` معنای پایدارتر و قابل‌توسعه‌تری می‌دهد.',
    deepDive:'ValueTuple با assignment کپی می‌شود، mutable است و equality component-wise دارد. نام elementها عمدتاً metadata و کمک Compiler هستند و هویت type را عوض نمی‌کنند؛ `(int X, int Y)` و `(int A, int B)` type سازگار دارند. `System.Tuple` object روی Heap است و propertyهایی مانند Item1 دارد. tuple طولانی، nested یا دارای چند مقدار هم‌type به‌سادگی اشتباه استفاده می‌شود و افزودن behavior یا validation به آن دشوار است.',
    exampleExplanation:'method با return `(bool Success, string? Error)` برای نتیجه داخلی ساده قابل‌فهم است و caller می‌تواند آن را deconstruct کند. برای پاسخ API شامل Status، ErrorCode و RetryAfter، record نام‌دار بهتر است چون معنا و evolution را روشن می‌کند. کپی ValueTuple مستقل است، مگر componentهای آن reference به object mutable باشند.',
    keyPoints:['ValueTuple یک Value Type و مناسب داده موقت است.','نام elementها قرارداد type مستقل ایجاد نمی‌کنند.','برای مدل پایدار و دارای behavior از type نام‌دار استفاده کنید.'],
    furtherDetails:'deconstruction فقط مخصوص tuple نیست و هر type می‌تواند method مناسب `Deconstruct` داشته باشد. تغییر نام element tuple معمولاً binary identity را تغییر نمی‌دهد، اما روی خوانایی source اثر دارد. در public API، record یا class نام‌دار نسخه‌پذیری و documentation بهتری فراهم می‌کند.'
  },
  'generic-benefits':{
    shortAnswer:'Genericها یک algorithm یا data structure را برای چند type با Type Safety مشترک می‌کنند. خطاهای type در Compile Time پیدا می‌شوند، castهای مصرف‌کننده حذف می‌شوند و برای Value Typeها معمولاً Boxing ناخواسته کاهش می‌یابد.',
    mentalModel:'`List<T>` را ظرفی بدانید که type محتوای آن بخشی از قرارداد است. `List<int>` فقط int می‌پذیرد و هنگام خواندن int تحویل می‌دهد؛ نیازی نیست caller حدس بزند داخل `object` چه بوده است. T یک جای خالی بی‌قانون نیست؛ Compiler تمام استفاده‌ها را با همان type واقعی بررسی می‌کند.',
    deepDive:'پیش از Genericها، collection مبتنی بر `object` هم cast لازم داشت و هم امکان خطای Runtime ایجاد می‌کرد. Generic method مانند `Max<T>` منطق را یک بار بیان می‌کند و Compiler type argument را infer یا validate می‌کند. constraints قابلیت‌های قابل‌استفاده روی T را محدود می‌کنند. در CLR، constructed generic typeها در Runtime شناخته می‌شوند؛ این مدل با type erasure ساده یکسان نیست. مزیت Performance وابسته به workload است و نباید بدون اندازه‌گیری ادعای مطلق کرد.',
    exampleExplanation:'`Stack<int>` فقط int می‌گیرد و `Pop` نیز int برمی‌گرداند، پس cast و احتمال `InvalidCastException` حذف می‌شود. همان implementation برای `Stack<Order>` استفاده می‌شود. اگر نسخه قدیمی `ArrayList` باشد، افزودن string کنار int ممکن است تا زمان cast بعدی پنهان بماند و intها نیز Boxing شوند.',
    keyPoints:['Genericها Type Safety را به قرارداد type منتقل می‌کنند.','یک implementation برای چند type قابل‌استفاده می‌شود.','برای Value Typeها می‌توانند Boxing ناخواسته را کم کنند.'],
    furtherDetails:'Generic همیشه بهترین abstraction نیست؛ اگر رفتار typeها واقعاً متفاوت است، یک T عمومی ممکن است شرط‌های فراوان بسازد. API را بر capability مشترک طراحی و کمترین constraint لازم را انتخاب کنید. برای مسیرهای حساس، allocation و generated code را با profiler و Benchmark بررسی کنید.'
  },
  'generic-constraints':{
    shortAnswer:'Generic Constraint به Compiler می‌گوید T چه قراردادی دارد؛ مانند `class`، `struct`، `notnull`، base class، interface یا `new()`. در نتیجه implementation می‌تواند memberهای تضمین‌شده را بدون cast فراخوانی کند.',
    mentalModel:'بدون constraint، درباره T تقریباً هیچ چیز جز قواعد مشترک typeها نمی‌دانیم. اگر algorithm باید `CompareTo` را صدا بزند، قرارداد `where T : IComparable<T>` همان capability موردنیاز را اعلام می‌کند. constraint برای محدودکردن تصادفی caller نیست؛ باید دلیل واقعی implementation را بیان کند.',
    deepDive:'constraintها هم Compile Time validation می‌دهند و هم surface قابل‌استفاده در بدنه Generic را تعیین می‌کنند. می‌توان چند interface و یک base constraint را ترکیب کرد، اما ترتیب syntax قواعد مشخص دارد. `new()` constructor بدون parameter عمومی را تضمین می‌کند. `notnull` بیشتر با nullable analysis مرتبط است. constraintهای `unmanaged`، `enum` و `delegate` سناریوهای خاص را پوشش می‌دهند. constraint بیش‌ازحد reuse را کاهش و evolution API را سخت می‌کند.',
    exampleExplanation:'در `Max<T> where T : IComparable<T>`، call به `CompareTo` ایمن است و استفاده با type فاقد این interface در Compile Time رد می‌شود. اگر فقط خواندن property Id لازم است، یک `IHasId` کوچک بهتر از مجبورکردن T به ارث از base class سنگین است. `new()` تنها construction بدون argument را تضمین می‌کند.',
    keyPoints:['constraint قابلیت‌های T را برای Compiler تضمین می‌کند.','کمترین قرارداد لازم انعطاف بیشتری حفظ می‌کند.','constraint جای validation داده‌های Runtime را نمی‌گیرد.'],
    furtherDetails:'`where T : class` و `where T : notnull` معنای یکسان ندارند؛ اولی Reference Type بودن را محدود می‌کند و دومی nullability contract را. static abstract memberهای interface امکان Generic Math را فراهم کرده‌اند و algorithm می‌تواند operatorهای type-safe را از constraint دریافت کند. در طراحی public API اثر هر constraint بر سازگاری آینده را بسنجید.'
  },
  'variance':{
    shortAnswer:'Covariance با `out` برای producer است: `IEnumerable<Dog>` را می‌توان به `IEnumerable<Animal>` داد. Contravariance با `in` برای consumer است: مصرف‌کننده Animal می‌تواند جای مصرف‌کننده Dog استفاده شود.',
    mentalModel:'قانون حفظی روشن است: producer خروجی می‌دهد، پس `out`؛ consumer ورودی می‌گیرد، پس `in`. فهرستی که فقط Dog تولید می‌کند با خیال راحت Animal هم تولید می‌کند. عملی که هر Animal را می‌پذیرد حتماً می‌تواند Dog را نیز بپذیرد. اگر type هم می‌خواند و هم می‌نویسد، معمولاً Invariant است.',
    deepDive:'variance روی Generic Interface و delegate declaration تعریف می‌شود و conversion آن فقط برای Reference Type argumentها کاربرد دارد. parameter covariant نباید در موقعیت ورودی مصرف شود، جز قواعد خاص delegate؛ parameter contravariant نباید به‌عنوان خروجی بازگردد. `IEnumerable<out T>` فقط T تولید می‌کند و `IComparer<in T>` T را مصرف می‌کند. این محدودیت‌ها همان چیزی است که conversion را type-safe نگه می‌دارد.',
    exampleExplanation:'`IEnumerable<string>` به `IEnumerable<object>` تبدیل می‌شود چون sequence فقط string بیرون می‌دهد و هر string یک object است. `Action<object>` می‌تواند در متغیر `Action<string>` قرار گیرد چون functionی که هر object را می‌پذیرد string را هم می‌پذیرد. جهت دوم هر دو conversion ایمن نیست.',
    keyPoints:['producer با `out` Covariant است.','consumer با `in` Contravariant است.','type خواندنی‌ونویشتنی معمولاً Invariant می‌ماند.'],
    furtherDetails:'variance conversion با Inheritance خود Generic Type متفاوت است؛ `List<T>` همچنان Invariant است. Value Type argumentها variance conversion نمی‌گیرند، چون conversion reference موردنیاز وجود ندارد. هنگام طراحی interface، parameter را فقط وقتی variant اعلام کنید که تمام memberها واقعاً جهت producer یا consumer را رعایت می‌کنند.'
  },
  'list-invariance':{
    shortAnswer:'`List<Dog>` به `List<Animal>` تبدیل نمی‌شود چون List هم T می‌خواند و هم T می‌نویسد. اگر conversion مجاز بود، caller می‌توانست Cat را در فهرستی اضافه کند که در واقع فقط Dog نگه می‌دارد.',
    mentalModel:'یک `List<Dog>` را موقتاً `List<Animal>` فرض کنید. API دوم حق دارد هر Animal، از جمله Cat، اضافه کند. پس فهرست اصلی دیگر List<Dog نیست و type safety شکسته می‌شود. ممنوع‌بودن conversion جلوی همین نوشتن ناسازگار را قبل از اجرا می‌گیرد.',
    deepDive:'`List<T>` به دلیل methodهایی مانند `Add(T)` و indexer خواندن/نوشتن، T را هم در موقعیت ورودی و هم خروجی استفاده می‌کند و بنابراین Invariant است. اگر مصرف‌کننده فقط enumeration می‌خواهد، می‌توان `IEnumerable<Animal>` پذیرفت؛ `IEnumerable<out T>` Covariant است و امکان mutation ندارد. arrayها در C# Covariant هستند اما این سازگاری تاریخی با check در Runtime و احتمال `ArrayTypeMismatchException` همراه است، پس الگوی ایمنی برای List محسوب نمی‌شود.',
    exampleExplanation:'`List<Cat>` مستقیماً به List<Animal> assign نمی‌شود. همان list به `IEnumerable<Animal>` قابل‌دادن است و caller فقط Animal می‌خواند. تبدیل با `Cast` type collection را عوض نمی‌کند؛ `ToList<Animal>` یک فهرست جدید می‌سازد و ownership و هزینه متفاوتی دارد.',
    keyPoints:['List به‌علت خواندن و نوشتن T، Invariant است.','Covariance فقط برای قرارداد producer مانند IEnumerable ایمن است.','کپی به List جدید با conversion view یکسان نیست.'],
    furtherDetails:'برای API فقط‌خواندنی بسته به نیاز از `IEnumerable<T>`، `IReadOnlyCollection<T>` یا `IReadOnlyList<T>` استفاده کنید؛ readonly interface به‌تنهایی object زیرین را immutable نمی‌کند. اگر mutation لازم است، type دقیق و ownership تغییرات را صریح نگه دارید.'
  },
  'clr-generics':{
    shortAnswer:'Genericها در CLR reified هستند؛ definition و type argumentهای ساخته‌شده در metadata و Runtime قابل‌شناسایی‌اند. JIT می‌تواند برای Reference Typeها code را share و برای Value Typeها code تخصصی تولید کند، اما جزئیات به Runtime وابسته است.',
    mentalModel:'`List<int>` و `List<string>` فقط نام‌های حذف‌شونده پس از Compile نیستند؛ Runtime می‌داند هرکدام چه type argumentی دارند. با Reflection می‌توان definition یعنی `List<>` و argument یعنی int یا string را دید. این شناخت اجازه می‌دهد type safety تا Runtime و metadata حفظ شود.',
    deepDive:'Compiler کد C# را همراه Generic metadata به IL تبدیل می‌کند. هنگام استفاده از یک constructed type، CLR layout و constraintها را می‌شناسد و JIT machine code لازم را تولید می‌کند. Reference Type instantiationها اغلب representation مشابه دارند و امکان code sharing بیشتر است؛ Value Typeها layout متفاوت دارند و specialization می‌تواند Boxing را حذف کند. این توضیح یک الگوی رایج است نه تضمین تعداد دقیق native bodyها در تمام نسخه‌ها و modeهای AOT/JIT.',
    exampleExplanation:'Reflection روی `Dictionary<string,int>` دو Generic Argument واقعی را برمی‌گرداند. method `Count<T>` برای List<string> و List<object> ممکن است machine code مشترک داشته باشد، درحالی‌که List<int> به‌دلیل layout value به code متفاوت نیاز پیدا کند. semantics هر سه همچنان type-safe و یکسان با قرارداد source است.',
    keyPoints:['Generic type argumentها در CLR حذف نمی‌شوند.','metadata definition و constructed type را نگه می‌دارد.','code sharing و specialization جزئیات Runtime هستند.'],
    furtherDetails:'از reification نتیجه نگیرید که برای هر T حتماً native code کاملاً جدا ساخته می‌شود. Tiered Compilation، ReadyToRun و Native AOT تصویر را تغییر می‌دهند. برای تصمیم Performance، allocation، code size و throughput را در target runtime واقعی اندازه بگیرید.'
  },
  'array-list-linkedlist':{
    shortAnswer:'Array اندازه ثابت و storage پیوسته دارد؛ `List<T>` یک آرایه رشدپذیر با دسترسی سریع index است؛ `LinkedList<T>` nodeهای جدا دارد و درج یا حذف O(1) را فقط وقتی node مقصد از قبل در اختیار باشد فراهم می‌کند.',
    mentalModel:'اگر تعداد معلوم و ثابت است Array ساده است. اگر فهرست معمولی با append و index می‌خواهید، List انتخاب پیش‌فرض خوبی است. LinkedList را زمانی بررسی کنید که node پایدار دارید و مرتباً کنار همان node درج یا حذف می‌کنید؛ پیدا کردن node خودش O(n) است.',
    deepDive:'List ظرفیت جدا از Count دارد و هنگام پرشدن، buffer بزرگ‌تری می‌گیرد و elementها را کپی می‌کند؛ append به‌صورت amortized O(1) است. Array و List locality خوبی دارند و cache CPU از traversal آن‌ها سود می‌برد. LinkedList برای هر element node و referenceهای اضافی دارد، allocation و locality ضعیف‌تری ایجاد می‌کند و دسترسی index آن O(n) است. Big-O بدون درنظرگرفتن جست‌وجو، allocation و locality انتخاب کامل نمی‌دهد.',
    exampleExplanation:'افزودن یک میلیون item و پیمایش ترتیبی معمولاً با List مناسب است. اگر marker یک `LinkedListNode<T>` را نگه می‌دارد و باید دائماً قبل از همان marker item درج شود، LinkedList می‌تواند هزینه جابه‌جایی array را حذف کند. اگر هر بار ابتدا value را جست‌وجو کنیم، مزیت O(1) درج تحت‌الشعاع جست‌وجوی O(n) قرار می‌گیرد.',
    keyPoints:['Array fixed-size و دارای locality خوب است.','List برای collection عمومی و indexمحور انتخاب رایج است.','LinkedList فقط با node موجود درج و حذف O(1) واقعی می‌دهد.'],
    furtherDetails:'با تعیین capacity اولیه List می‌توان resizeهای قابل‌پیش‌بینی را کم کرد. `Span<T>` view کم‌هزینه روی storage پیوسته است اما Collection عمومی و قابل‌ذخیره‌سازی روی Heap نیست. انتخاب را با الگوی واقعی access و Benchmark انجام دهید، نه صرفاً جدول Big-O.'
  },
  'dictionary-hashing':{
    shortAnswer:'`Dictionary<TKey,TValue>` ابتدا با hash کلید محدوده جست‌وجو را به bucket کاهش می‌دهد و سپس با equality کلید دقیق را پیدا می‌کند. هر دو کلید برابر باید hash یکسان داشته باشند و کلید هنگام عضویت نباید از نظر equality تغییر کند.',
    mentalModel:'hash آدرس نهایی نیست؛ یک راهنمای سریع برای رسیدن به گروه کوچکی از candidateهاست. چون چند کلید می‌توانند hash یکسان داشته باشند، Dictionary در پایان equality را بررسی می‌کند. پس hash خوب collision را کم می‌کند، اما درست‌بودن equality تعیین‌کننده هویت کلید است.',
    deepDive:'عملیات معمول lookup میانگین نزدیک O(1) دارد، اما collision زیاد یا comparer بد می‌تواند کار را افزایش دهد. invariant اصلی این است: اگر `Equals(a,b)` true است، `GetHashCode` آن‌ها باید برابر باشد؛ عکس آن لازم نیست. comparer انتخاب‌شده هم hash و هم equality را تعریف می‌کند. mutation fieldهای مؤثر در hash پس از insert باعث می‌شود lookup در bucket جدید بگردد درحالی‌که entry در bucket قبلی مانده است.',
    exampleExplanation:'Dictionary با `StringComparer.OrdinalIgnoreCase` کلیدهای `Sara` و `sara` را یکسان می‌بیند چون comparer برای هر دو hash و equality سازگار دارد. `TryGetValue` lookup را یک بار انجام می‌دهد. اگر یک record mutable به‌عنوان key استفاده و property مؤثر در equality تغییر کند، بازیابی آن ممکن است شکست بخورد.',
    keyPoints:['hash bucket candidateها را پیدا می‌کند و equality کلید نهایی را.','کلیدهای برابر باید hash یکسان تولید کنند.','کلید mutable می‌تواند invariant Dictionary را بشکند.'],
    furtherDetails:'در string key، comparer را از قرارداد دامنه انتخاب کنید؛ نام کاربری، path و identifier قواعد یکسانی ندارند. hash برای امنیت رمزنگاری نیست. اگر ترتیب لازم است از contract مربوط استفاده کنید و به ترتیب مشاهده‌شده Dictionary به‌عنوان فرض پنهان تکیه نکنید.'
  },
  'collection-interfaces':{
    shortAnswer:'`IEnumerable<T>` قرارداد پیمایش است؛ `ICollection<T>` Count و عملیات افزودن/حذف مجموعه را اضافه می‌کند؛ `IList<T>` دسترسی و mutation براساس index را نیز تضمین می‌کند. API باید کم‌قدرت‌ترین contract کافی را بپذیرد.',
    mentalModel:'هر interface یک مجوز به function می‌دهد. IEnumerable فقط اجازه دیدن itemها را می‌دهد. ICollection اجازه تغییر اندازه و دانستن Count را اضافه می‌کند. IList علاوه بر آن می‌گوید ترتیب و index معنی دارد. اگر function فقط جمع می‌زند، درخواست IList اختیار اضافی و بی‌دلیل است.',
    deepDive:'IEnumerable می‌تواند lazy، remote، stateful یا یک‌بارمصرف باشد؛ enumeration دوباره الزاماً رایگان یا حتی هم‌نتیجه نیست. ICollection معمولاً materialized collection با Count و mutation را بیان می‌کند، هرچند `IsReadOnly` می‌تواند عملیات mutation را محدود کند. IList indexer و Insert/RemoveAt دارد و برای sequence مرتب مناسب است. interfaceهای readonly قابلیت mutation را از view مصرف‌کننده حذف می‌کنند، ولی object زیرین را deep immutable نمی‌سازند.',
    exampleExplanation:'`Total(IEnumerable<Order>)` روی Array، List یا query کار می‌کند چون فقط enumeration لازم دارد. methodی که item اضافه می‌کند `ICollection<Order>` می‌خواهد. UI که drag-and-drop براساس position انجام می‌دهد ممکن است `IList<Order>` لازم داشته باشد. فراخوانی Count با `enumerable.Count()` روی query می‌تواند query جدا اجرا کند.',
    keyPoints:['IEnumerable فقط پیمایش را قرارداد می‌کند.','ICollection Count و mutation مجموعه را اضافه می‌کند.','IList semantics مربوط به index و ترتیب را اضافه می‌کند.'],
    furtherDetails:'در خروجی API، `IReadOnlyList<T>` intent فقط‌خواندن و index را روشن می‌کند، اما برای جلوگیری از mutation خارجی شاید defensive copy یا Immutable Collection لازم باشد. چندبار enumerate کردن ورودی ناشناخته را مستند یا یک‌بار materialize کنید؛ این تصمیم هزینه حافظه و زمان دارد.'
  },
  'set-and-map-choices':{
    shortAnswer:'`HashSet<T>` برای membership و uniqueness سریع است؛ `SortedSet<T>` uniqueness را با ترتیب مرتب و range operation ترکیب می‌کند؛ `Dictionary<TKey,TValue>` وقتی هر key باید به یک value مرتبط نگاشت شود مناسب است.',
    mentalModel:'مسئله را به سه سؤال تبدیل کنید: فقط می‌خواهم بدانم item وجود دارد؟ HashSet. باید itemهای یکتا همیشه مرتب باشند؟ SortedSet. برای هر key داده دیگری دارم؟ Dictionary. انتخاب بر نام collection نیست؛ بر operation اصلی و contract ترتیب است.',
    deepDive:'HashSet از hashing و equality استفاده می‌کند و ترتیب enumeration آن نباید contract برنامه باشد. SortedSet ساختار مرتب مبتنی بر comparer دارد، operationهای membership معمولاً O(log n) هستند و viewهای range فراهم می‌کند. Dictionary نیز hashing دارد ولی entry شامل key و value است. استفاده از `Dictionary<T,bool>` برای membership intent را ضعیف و حافظه اضافی مصرف می‌کند. comparer در هر سه باید با قواعد دامنه سازگار باشد.',
    exampleExplanation:'برای حذف tagهای تکراری با مقایسه case-insensitive از HashSet استفاده می‌شود. برای leaderboard یکتا که همیشه براساس score مرتب و نیازمند Min/Max است SortedSet مناسب‌تر است. catalog قیمت به Dictionary نیاز دارد چون هر product code به decimal نگاشت می‌شود.',
    keyPoints:['HashSet پاسخ membership و uniqueness می‌دهد.','SortedSet ترتیب مرتب و range را حفظ می‌کند.','Dictionary رابطه key-to-value را مدل می‌کند.'],
    furtherDetails:'اگر چند value برای یک key لازم است، Dictionary با collection value یا `Lookup` را بررسی کنید. اگر ترتیب insertion قرارداد است، type مناسب همان contract را صریح انتخاب کنید و به جزئیات implementation تکیه نکنید. هزینه comparer و mutation کلیدها نیز مانند Dictionary مهم است.'
  },
  'concurrent-immutable':{
    shortAnswer:'Concurrent Collection mutation مشترک بین threadها را هماهنگ می‌کند؛ Immutable Collection به‌جای تغییر object قبلی، snapshot جدید می‌سازد. اولی برای state پرتغییر مشترک و دومی برای انتشار state پایدار و خواندن فراوان مناسب است.',
    mentalModel:'در مدل concurrent چند نفر روی یک تخته مشترک با ابزار هماهنگ می‌نویسند. در مدل immutable هر نسخه تخته پس از انتشار عوض نمی‌شود و نویسنده نسخه تازه می‌سازد. reader نسخه‌ای ثابت می‌بیند، ولی writer باید reference نسخه جدید را به‌درستی منتشر کند.',
    deepDive:'methodهای منفرد Concurrent Collection thread-safe هستند، اما ترکیب check-then-act چندمرحله‌ای لزوماً atomic نیست؛ باید از operation ترکیبی مناسب یا synchronization بیرونی استفاده کرد. در `ConcurrentDictionary.GetOrAdd` value factory ممکن است در رقابت بیش از یک بار اجرا شود، هرچند تنها یک value ذخیره شود؛ side effect خطرناک است. Immutable Collection با structural sharing هزینه copy کامل را کاهش می‌دهد، اما allocation و publication نسخه جدید همچنان وجود دارد.',
    exampleExplanation:'cache پرترافیک از ConcurrentDictionary استفاده می‌کند، اما `Load` در GetOrAdd باید تحمل اجرای چندباره داشته باشد یا Lazy مناسبی ذخیره شود. تنظیمات برنامه با ImmutableDictionary ساخته و reference snapshot جدید atomically منتشر می‌شود؛ reader بدون lock همان نسخه ثابت را تا پایان پردازش می‌خواند.',
    keyPoints:['thread-safe بودن collection کل workflow را atomic نمی‌کند.','factory مربوط به GetOrAdd ممکن است چند بار اجرا شود.','Immutable Collection snapshot پایدار می‌دهد، نه publication خودکار.'],
    furtherDetails:'گاهی ownership تک‌thread و message passing از هر دو ساده‌تر است. نوع workload، نسبت read/write، نیاز به snapshot consistency و هزینه allocation معیار انتخاب‌اند. برای invariant چند collection، یک lock یا state immutable واحد می‌تواند از operationهای جدا و ظاهراً thread-safe درست‌تر باشد.'
  }
};
